//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETSUACHUA
    {
        public int MACTSC { get; set; }
        public int MASUACHUA { get; set; }
        public string NOIDUNGSC { get; set; }
        public Nullable<int> SOLUONGSC { get; set; }
        public Nullable<decimal> TONGTIENSC { get; set; }
        public string GHICHUSC { get; set; }
    
        public virtual SUACHUA SUACHUA { get; set; }
    }
}
