//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETPHANCONG
    {
        public string TENDNTX { get; set; }
        public int MAXE { get; set; }
        public System.DateTime NGAYBATDAU { get; set; }
        public string GHICHUPC { get; set; }
    
        public virtual PHANCONG PHANCONG { get; set; }
        public virtual TAIXE TAIXE { get; set; }
        public virtual XE XE { get; set; }
    }
}
