//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATXE
    {
        public int MADX { get; set; }
        public int MATRANGTHAI { get; set; }
        public Nullable<int> MAXE { get; set; }
        public string TENDN { get; set; }
        public int MALOAIXE { get; set; }
        public Nullable<System.DateTime> NGAYDX { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public Nullable<System.DateTime> NGAYVE { get; set; }
        public string GIODI { get; set; }
        public string GIOVE { get; set; }
        public string LOTRINHDI { get; set; }
        public Nullable<float> SOKMDI { get; set; }
        public string LOTRINHVE { get; set; }
        public Nullable<float> SOKMVE { get; set; }
        public string GHICHUDUYET { get; set; }
        public Nullable<int> SOLUONGDOAN { get; set; }
        public string CHUTRIDOAN { get; set; }
    
        public virtual LOAIXE LOAIXE { get; set; }
        public virtual TRANGTHAIXE TRANGTHAIXE { get; set; }
        public virtual USER USER { get; set; }
        public virtual XE XE { get; set; }
    }
}
