//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phancongtx
    {
        public System.DateTime NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string TENDN { get; set; }
        public string TENDNTX { get; set; }
        public string HOTENTX { get; set; }
        public string CHANDUNG { get; set; }
        public int MAXE { get; set; }
        public string NHANHIEU { get; set; }
        public string BIENSO { get; set; }
        public string HINHXE { get; set; }
    }
}
