//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHANCONG()
        {
            this.CHITIETPHANCONGs = new HashSet<CHITIETPHANCONG>();
        }
    
        public System.DateTime NGAYBATDAU { get; set; }
        public string TENDN { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHANCONG> CHITIETPHANCONGs { get; set; }
        public virtual USER USER { get; set; }
    }
}
