//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIKHAC
    {
        public int MAPHI { get; set; }
        public int MAXE { get; set; }
        public string NOIDUNGPHI { get; set; }
        public Nullable<decimal> TONGPHI { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public string NOITHUCHIEN { get; set; }
        public string HOADONPHI { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
