//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thongtinxe
    {
        public int MAXE { get; set; }
        public string BIENSO { get; set; }
        public string NHANHIEU { get; set; }
        public string TENLOAIXE { get; set; }
        public string HOPSO { get; set; }
        public string NHIENLIEU { get; set; }
        public string TENTINHTRANG { get; set; }
        public Nullable<System.DateTime> HANLUUHANH { get; set; }
        public Nullable<System.DateTime> HANBAOHIEM { get; set; }
        public string HINHXE { get; set; }
        public int MATINHTRANG { get; set; }
    }
}
