//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.DATXEs = new HashSet<DATXE>();
            this.PHANCONGs = new HashSet<PHANCONG>();
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public string TENDN { get; set; }
        public Nullable<int> MAKHOA { get; set; }
        public int MACHUCVU { get; set; }
        public string MATKHAU { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NAMSINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CMND { get; set; }
        public string AVATAR { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATXE> DATXEs { get; set; }
        public virtual KHOA KHOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
