//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DatxeTaixe
    {
        public string TENDNTX { get; set; }
        public string HOTENTX { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public Nullable<System.DateTime> NGAYVE { get; set; }
        public Nullable<int> MAXE { get; set; }
        public string NHANHIEU { get; set; }
        public string BIENSO { get; set; }
        public string TENTRANGTHAI { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NGAYDX { get; set; }
        public int MADX { get; set; }
        public int MATRANGTHAI { get; set; }
        public string LOTRINHDI { get; set; }
        public Nullable<float> SOKMDI { get; set; }
        public string LOTRINHVE { get; set; }
        public Nullable<float> SOKMVE { get; set; }
        public string CHANDUNG { get; set; }
        public string HINHXE { get; set; }
    }
}
