//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Taikhoan
    {
        public string TENDN { get; set; }
        public Nullable<int> MAKHOA { get; set; }
        public string TENKHOA { get; set; }
        public int MACHUCVU { get; set; }
        public string TENCHUCVU { get; set; }
        public string HOTEN { get; set; }
        public Nullable<System.DateTime> NAMSINH { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CMND { get; set; }
        public string AVATAR { get; set; }
    }
}
