//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XANGLOP
    {
        public int MAXANGLOP { get; set; }
        public int MAXE { get; set; }
        public string DIADIEM { get; set; }
        public Nullable<System.DateTime> NGAYDO { get; set; }
        public Nullable<float> SOLUONG { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string ANHHOADON { get; set; }
        public string LOAIHINH { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
