//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyXe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.CHITIETPHANCONGs = new HashSet<CHITIETPHANCONG>();
            this.DATXEs = new HashSet<DATXE>();
            this.PHIKHACs = new HashSet<PHIKHAC>();
            this.SUACHUAs = new HashSet<SUACHUA>();
            this.THONGKETHANGs = new HashSet<THONGKETHANG>();
            this.XANGLOPs = new HashSet<XANGLOP>();
        }
    
        public int MAXE { get; set; }
        public int MALOAIXE { get; set; }
        public int MATINHTRANG { get; set; }
        public string BIENSO { get; set; }
        public string NHANHIEU { get; set; }
        public string HOPSO { get; set; }
        public string NHIENLIEU { get; set; }
        public Nullable<System.DateTime> HANLUUHANH { get; set; }
        public Nullable<System.DateTime> HANBAOHIEM { get; set; }
        public string HINHXE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETPHANCONG> CHITIETPHANCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATXE> DATXEs { get; set; }
        public virtual LOAIXE LOAIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIKHAC> PHIKHACs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUACHUA> SUACHUAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGKETHANG> THONGKETHANGs { get; set; }
        public virtual TINHTRANGXE TINHTRANGXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XANGLOP> XANGLOPs { get; set; }
    }
}
